# Generated by Django 3.2.4 on 2024-01-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240103_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='RegistroCliente',
        ),
        migrations.DeleteModel(
            name='RegistroC',
        ),
    ]
