# Generated by Django 3.2.4 on 2024-01-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_problemac'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemaC',
            new_name='ProblemaClientes',
        ),
    ]
